main: me.zombie_striker.pluginconstructor.PluginConstructorAPI
version: 1.0.46
api-version: 1.13
name: PluginConstructorAPI
author:
   Zombie_Striker
commands:
  PluginConstructorAPI:
    description: Useful for accessing features for pluginconstructor while in-game
    aliases: [pcapi]
permissions:
   pluginconstructorapi.*:
     description: Gives access to all PluginConstructorAPI commands
     children:
       pluginconstructorapi.download: true